### PR TITLE
Fix #10: Add strings where needed

### LINKED ISSUE #10: Quote strings
Aside from `left` and `right` which are rather positions than strings, it's best practice to quote strings in Sass to help figuring out what's going on.

I'm mostly thinking of `$direction` in `align` and the like.

### PR DESCRIPTION
**Pull request by jakecleary**
@HugoGiraudel thought I would PR so you could check it over if you don't mind?

Let me know what you think.

### CODE REVIEW

**Comment by KittyGiraudel** [comment]
So you went with single quotes?

**Comment by corysimmons** [comment]
Sass convention is double quotes right?

**Comment by KittyGiraudel** [comment]
I don't know if there are many conventions about this. I'd say CSS/Sass is more oriented to double quotes, yep.

**Comment by jakecleary** [comment]
Sorry, I'm used to double for interpolation in php etc. Will fix.

**Comment by jakecleary** [comment]
How about now @HugoGiraudel?

**Comment by KittyGiraudel** [comment]
Looks nice I think. :)

**Comment by corysimmons** [comment]
:+1:

**Comment by jakecleary** [comment]
Cool will merge. Thanks guys.

**Pull request merged**
